import Database from "../config/database";
import {
    User,
    UserProfile,
    MealPlan,
    MealPlanItem,
    Recipe,
    RecipeIngredient,
    MealType,
} from "../models";
import { GoogleGeminiModel } from "./llmService";
import { IngredientService } from "./ingredientService";
import { CategoryService } from "./categoryService";
import {
    buildSingleDayMealPlanPrompt,
    GeneratedRecipe,
} from "../utils/prompt.builder";
import { BadRequestError } from "../core/error.response";
import { Repository } from "typeorm";

/**
 * Interface for AI response - creates NEW recipes with full details
 */
interface AIRecipeResponse {
    name: string;
    description: string;
    image_url: string;
    cuisine_type: string;
    difficulty_level: "easy" | "medium" | "hard";
    prep_time_minutes: number;
    cook_time_minutes: number;
    servings: number;
    ingredients: Array<{
        name: string;
        quantity: number;
        unit: string;
        category_name?: string; // Optional category name from AI
    }>;
    instructions: string;
    nutritional_info: {
        calories: number;
        protein: number;
        carbs: number;
        fats: number;
    };
}

export class MealPlanService {
    private llmService: GoogleGeminiModel;
    private ingredientService: IngredientService;
    private categoryService: CategoryService;

    constructor() {
        this.llmService = new GoogleGeminiModel();
        this.ingredientService = new IngredientService();
        this.categoryService = new CategoryService();
    }

    /**
     * Generate remaining days of meal plan using AI - ONE DAY AT A TIME
     * Creates NEW recipes (doesn't select from existing)
     * Saves each day immediately after generation to avoid data loss
     *
     * @param userId - User ID
     * @param numDays - Number of days to generate (default 6 for days 2-7)
     */
    async generateRemainingWeekDays(
        userId: string,
        numDays: number = 6
    ): Promise<{
        mealPlanId: string;
        message: string;
        details: any;
        startDate: string;
        endDate: string;
    }> {
        console.log(`[INFO] - Generating ${numDays} days for user ${userId}`);

        try {
            // 1. Get user and profile
            const userRepo = Database.getRepository(User);
            const profileRepo = Database.getRepository(UserProfile);
            const mealPlanRepo = Database.getRepository(MealPlan);

            const user = await userRepo.findOne({ where: { id: userId } });
            if (!user) {
                throw new BadRequestError("User not found");
            }

            const profile = (await profileRepo.findOne({
                where: { user: { id: userId } },
            })) as UserProfile | null;

            // 2. Get recipe history to avoid duplicates
            const recipeHistory = await this.getUserMealPlanHistory(
                userId,
                mealPlanRepo as Repository<MealPlan>
            );
            console.log(
                `[INFO] - Retrieved ${recipeHistory.length} past meal plans for history`
            );

            // 3. Calculate generation start (tomorrow) and end based on numDays
            const today = new Date();
            today.setHours(0, 0, 0, 0);
            const startDate = new Date(today);
            startDate.setDate(startDate.getDate() + 2);
            const startDateStr = startDate.toISOString().split("T")[0];
            const endDate = new Date(startDate);
            endDate.setDate(endDate.getDate() + numDays - 1);
            const endDateStr = endDate.toISOString().split("T")[0];

            // 4. Find or create meal plan (do this ONCE at the beginning)
            let mealPlan = await mealPlanRepo.findOne({
                where: {
                    user: { id: userId },
                    start_date: startDateStr,
                    end_date: endDateStr,
                    is_active: true,
                },
            });

            if (!mealPlan) {
                mealPlan = new MealPlan();
                mealPlan.user = { id: userId } as User;
                mealPlan.name = `AI Weekly Plan - ${startDateStr}`;
                mealPlan.start_date = startDateStr;
                mealPlan.end_date = endDateStr;
                mealPlan.ai_generated = true;
                mealPlan.is_active = true;
                mealPlan.notes = `Generated by AI Meal Plan Server (${numDays} days, iterative)`;

                mealPlan = await mealPlanRepo.save(mealPlan);
                console.log(
                    `[SUCCESS] - Created new meal plan: ${mealPlan.id}`
                );
            } else {
                console.log(
                    `[SUCCESS] - Using existing meal plan: ${mealPlan.id}`
                );
            }

            // 5. Track recipes generated in this session for uniqueness
            const currentSessionRecipes: GeneratedRecipe[] = [];
            let totalSavedItems = 0;
            const generationResults = [];

            // 6. GENERATE EACH DAY ONE BY ONE
            for (let dayIndex = 0; dayIndex < numDays; dayIndex++) {
                const currentDate = new Date(startDate);
                currentDate.setDate(currentDate.getDate() + dayIndex);
                const currentDateStr = currentDate.toISOString().split("T")[0];

                console.log(
                    `[INFO] - Generating day ${
                        dayIndex + 1
                    } (${currentDateStr})...`
                );

                try {
                    // Get available categories from database
                    const availableCategories =
                        await this.categoryService.getCategoriesForAI();

                    // Build prompt for single day with current session recipes
                    const prompt = buildSingleDayMealPlanPrompt(
                        profile || {},
                        currentDateStr,
                        recipeHistory,
                        currentSessionRecipes,
                        availableCategories
                    );

                    console.log(
                        `[INFO] - Calling AI for day ${currentDateStr}...`
                    );

                    // Call AI to generate ONE day
                    const aiResponse = await this.llmService.generateResponse(
                        prompt
                    );

                    if (
                        !aiResponse.success ||
                        !aiResponse.plans ||
                        aiResponse.plans.length === 0
                    ) {
                        console.error(
                            `[ERROR] - Failed to generate day ${currentDateStr}`
                        );
                        generationResults.push({
                            date: currentDateStr,
                            success: false,
                            error: "AI generation failed",
                        });
                        continue; // Skip this day but continue with next
                    }

                    const dayPlan = aiResponse.plans[0]; // Should only have 1 day

                    // Validate day
                    if (!dayPlan.meals || dayPlan.meals.length !== 3) {
                        console.error(
                            `[WARNING] - Invalid day structure for ${currentDateStr}`
                        );
                        generationResults.push({
                            date: currentDateStr,
                            success: false,
                            error: "Invalid meal structure",
                        });
                        continue;
                    }

                    // Save this day's recipes and meal plan items
                    let dayItemsCount = 0;
                    const dayRecipes: GeneratedRecipe[] = [];

                    // Use transaction for each day
                    const queryRunner =
                        Database.getInstance().createQueryRunner();
                    await queryRunner.connect();
                    await queryRunner.startTransaction();

                    try {
                        for (const meal of dayPlan.meals) {
                            for (const aiRecipe of meal.recipes) {
                                // Create NEW recipe from AI response
                                const recipe = await this.createRecipeFromAI(
                                    aiRecipe,
                                    userId,
                                    queryRunner
                                );

                                // Create meal plan item
                                const mealPlanItem = new MealPlanItem();
                                mealPlanItem.meal_plan = mealPlan as MealPlan;
                                mealPlanItem.recipe = recipe;
                                mealPlanItem.meal_date = meal.meal_date;
                                mealPlanItem.meal_type =
                                    meal.meal_type as MealType;
                                mealPlanItem.servings = aiRecipe.servings;
                                mealPlanItem.is_completed = false;

                                await queryRunner.manager.save(
                                    MealPlanItem,
                                    mealPlanItem
                                );
                                dayItemsCount++;

                                // Track this recipe for uniqueness in next days
                                dayRecipes.push({
                                    name: aiRecipe.name,
                                    date: currentDateStr,
                                    meal_type: meal.meal_type,
                                    main_ingredients: aiRecipe.ingredients
                                        .slice(0, 3)
                                        .map((ing: any) => ing.name),
                                });
                            }
                        }

                        await queryRunner.commitTransaction();
                        console.log(
                            `[SUCCESS] - Day ${currentDateStr} saved: ${dayItemsCount} items`
                        );

                        // Add to session history
                        currentSessionRecipes.push(...dayRecipes);
                        totalSavedItems += dayItemsCount;

                        generationResults.push({
                            date: currentDateStr,
                            success: true,
                            items: dayItemsCount,
                            recipes: dayRecipes.map((r) => r.name),
                        });
                    } catch (error) {
                        await queryRunner.rollbackTransaction();
                        console.error(
                            `[ERROR] - Error saving day ${currentDateStr}:`,
                            error
                        );
                        generationResults.push({
                            date: currentDateStr,
                            success: false,
                            error: (error as Error).message,
                        });
                    } finally {
                        await queryRunner.release();
                    }
                } catch (error) {
                    console.error(
                        `[ERROR] - Error generating day ${currentDateStr}:`,
                        error
                    );
                    generationResults.push({
                        date: currentDateStr,
                        success: false,
                        error: (error as Error).message,
                    });
                }

                // Small delay between API calls to avoid rate limiting
                if (dayIndex < numDays - 1) {
                    await new Promise((resolve) => setTimeout(resolve, 1000));
                }
            }

            // 8. Summary
            const successfulDays = generationResults.filter(
                (r) => r.success
            ).length;
            const failedDays = generationResults.filter(
                (r) => !r.success
            ).length;

            console.log(`[SUCCESS] - Meal plan generation complete`);
            console.log(
                `[INFO] - Successful: ${successfulDays}/${numDays} days`
            );
            console.log(`[INFO] - Failed: ${failedDays} days`);
            console.log(`[INFO] - Total items saved: ${totalSavedItems}`);

            return {
                mealPlanId: mealPlan.id,
                message: `${successfulDays}/${numDays} days generated successfully`,
                details: {
                    start_date: mealPlan.start_date,
                    end_date: mealPlan.end_date,
                    days_requested: numDays,
                    days_successful: successfulDays,
                    days_failed: failedDays,
                    items_saved: totalSavedItems,
                    generation_results: generationResults,
                },
                startDate: startDate.toISOString().split("T")[0],
                endDate: endDate.toISOString().split("T")[0],
            };
        } catch (error) {
            console.error("[ERROR] - Error in meal plan generation:", error);
            throw error;
        }
    }

    /**
     * Create recipe from AI response
     */
    private async createRecipeFromAI(
        aiRecipe: AIRecipeResponse,
        userId: string,
        queryRunner: any
    ): Promise<Recipe> {
        // Create recipe
        const recipe = new Recipe();
        recipe.name = aiRecipe.name;
        recipe.description = aiRecipe.description;
        recipe.image_url =
            aiRecipe.image_url ||
            "https://via.placeholder.com/400x300?text=Recipe";
        recipe.cuisine_type = aiRecipe.cuisine_type;
        recipe.difficulty_level = aiRecipe.difficulty_level;
        recipe.prep_time_minutes = aiRecipe.prep_time_minutes;
        recipe.cook_time_minutes = aiRecipe.cook_time_minutes;
        recipe.servings = aiRecipe.servings;
        recipe.instructions = aiRecipe.instructions;
        recipe.created_by = userId;
        recipe.ai_generated = true;
        recipe.is_active = true;
        recipe.is_public = false;

        const savedRecipe = await queryRunner.manager.save(Recipe, recipe);

        // Create ingredients and recipe_ingredients using IngredientService
        for (let i = 0; i < aiRecipe.ingredients.length; i++) {
            const aiIngredient = aiRecipe.ingredients[i];

            // Find or create ingredient using IngredientService with category
            const ingredient =
                await this.ingredientService.findOrCreateIngredient(
                    aiIngredient.name,
                    queryRunner,
                    aiIngredient.category_name // Pass category name from AI
                );

            // Create recipe_ingredient
            const recipeIngredient = new RecipeIngredient();
            recipeIngredient.recipe_id = savedRecipe.id;
            recipeIngredient.ingredient_id = ingredient.id;
            recipeIngredient.recipe = savedRecipe;
            recipeIngredient.ingredient = ingredient;
            recipeIngredient.quantity = aiIngredient.quantity;
            recipeIngredient.unit = aiIngredient.unit;
            recipeIngredient.is_optional = false;
            recipeIngredient.sort_order = i + 1;

            await queryRunner.manager.save(RecipeIngredient, recipeIngredient);
        }

        return savedRecipe;
    }

    /**
     * Get user's meal plan history to avoid duplicates
     */
    private async getUserMealPlanHistory(
        userId: string,
        mealPlanRepo: Repository<MealPlan>
    ): Promise<MealPlan[]> {
        try {
            const recentPlans = await mealPlanRepo.find({
                where: {
                    user: { id: userId },
                    is_active: true,
                },
                relations: ["mealPlanItems", "mealPlanItems.recipe"],
                order: {
                    start_date: "DESC",
                },
                take: 10,
            });

            return recentPlans;
        } catch (error) {
            console.warn("[WARNING] - Could not fetch recipe history:", error);
            return [];
        }
    }
}

export default new MealPlanService();
